src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $codigo;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nombre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $descripcion;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $marca;

    /**
     * @ORM\Column(type="integer")
     */
    private $categoria_id;

    /**
     * @ORM\Column(type="float")
     */
    private $precio;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Categorias", inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categoria;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCodigo(): ?string
    {
        return $this->codigo;
    }

    public function setCodigo(string $codigo): self
    {
        $this->codigo = $codigo;

        return $this;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->descripcion;
    }

    public function setDescripcion(string $descripcion): self
    {
        $this->descripcion = $descripcion;

        return $this;
    }

    public function getMarca(): ?string
    {
        return $this->marca;
    }

    public function setMarca(string $marca): self
    {
        $this->marca = $marca;

        return $this;
    }

    public function getCategoriaId(): ?int
    {
        return $this->categoria_id;
    }

    public function setCategoriaId(int $categoria_id): self
    {
        $this->categoria_id = $categoria_id;

        return $this;
    }

    public function getPrecio(): ?float
    {
        return $this->precio;
    }

    public function setPrecio(float $precio): self
    {
        $this->precio = $precio;

        return $this;
    }

    public function getCategoria(): ?Categorias
    {
        return $this->categoria;
    }

    public function setCategoria(?Categorias $categoria): self
    {
        $this->categoria = $categoria;

        return $this;
    }
}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Product;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('codigo')
            ->add('nombre')
            ->add('descripcion')
            ->add('marca')
            ->add('categoria_id')
            ->add('precio')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Form\ProductType;
use App\Repository\ProductRepository;
use App\Repository\CategoriasRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/productos")
 */
class ProductController extends AbstractController
{
    /**
     * @Route("/", name="product_index", methods={"GET"})
     */
    public function index(ProductRepository $productRepository): Response
    {
        return $this->render('product/index.html.twig', [
            'products' => $productRepository->findAll(),
        ]);
    }

    /**
     * @Route("/nuevo_producto", name="product_new", methods={"GET","POST"})
     */
    public function new(Request $request,CategoriasRepository $categoriasRepository): Response
    {
        $categorias = $categoriasRepository->findAll();
        $product = new Product();
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($product);
            $entityManager->flush();

            return $this->redirectToRoute('product_index');
        }

        return $this->render('product/new.html.twig', [
            'product' => $product,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="product_show", methods={"GET"})
     */
    public function show(Product $product): Response
    {
        return $this->render('product/show.html.twig', [
            'product' => $product,
        ]);
    }

    /**
     * @Route("/{id}/editar_producto", name="product_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Product $product): Response
    {
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('product_index', [
                'id' => $product->getId(),
            ]);
        }
        return $this->render('product/edit.html.twig', [
            'product' => $product,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="product_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Product $product): Response
    {
        if ($this->isCsrfTokenValid('delete'.$product->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($product);
            $entityManager->flush();
        }

        return $this->redirectToRoute('product_index');
    }
}

templates/product/_delete_form.html.twig
<form method="post" action="{{ path('product_delete', {'id': product.id}) }}" onsubmit="return confirm('Estás seguro de querer eliminar este producto?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product.id) }}">
    <button class="btn btn-danger">Eliminar</button>
</form>

templates/product/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
     <button class="btn btn-primary">{{ button_label|default('Guardar') }}</button>
     <a class="btn btn-warning" href="{{ path('product_index') }}">Regresar</a>
{{ form_end(form) }}

templates/product/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editar Producto{% endblock %}

{% block body %}
    <h1>Editar producto</h1>

    {{ include('product/_form.html.twig', {'button_label': 'Actualizar'}) }}


{% endblock %}

templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Listado de productos{% endblock %}

{% block body %}
<br><br><br>
    <h1 style="text-align: center;">Listado de productos</h1>
    
<br><br><br>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th style="text-align: center;">Id</th>
                <th style="text-align: center;">Codigo</th>
                <th style="text-align: center;">Nombre</th>
                <th style="text-align: center;">Descripcion</th>
                <th style="text-align: center;">Marca</th>
                <th style="text-align: center;">Categoria</th>
                <th style="text-align: center;">Precio</th>
                <th style="text-align: center;">actions</th>
            </tr>
        </thead>
        <tbody>
        {% for product in products %}
            <tr>
                <td style="text-align: center;">{{ product.id }}</td>
                <td style="text-align: center;">{{ product.codigo }}</td>
                <td style="text-align: center;">{{ product.nombre }}</td>
                <td style="text-align: center;">{{ product.descripcion }}</td>
                <td style="text-align: center;">{{ product.marca }}</td>
                <td style="text-align: center;">{{ product.categoria.nombre }}</td>
                <td style="text-align: center;">{{ product.precio }}</td>
                <td style="text-align: center;">
                    {{ include('product/_delete_form.html.twig') }}
                    <a class="btn btn-warning  " href="{{ path('product_edit', {'id': product.id}) }}">Editar</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">No hay registros</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <a class="btn btn-info btn-sm " href="{{ path('product_new') }}">Crear producto</a>
    <a class="btn btn-success btn-sm " href="{{ path('categorias_index') }}">Ir a categorias</a>

</a>
{% endblock %}

templates/product/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nuevo Producto{% endblock %}

{% block body %}

<h1 >Nuevo Producto</h1>
<div class="container">
         {{ include('product/_form.html.twig') }}
     
</div>


{% endblock %}

templates/product/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Product{% endblock %}

{% block body %}
    <h1>Product</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ product.id }}</td>
            </tr>
            <tr>
                <th>Codigo</th>
                <td>{{ product.codigo }}</td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td>{{ product.nombre }}</td>
            </tr>
            <tr>
                <th>Descripcion</th>
                <td>{{ product.descripcion }}</td>
            </tr>
            <tr>
                <th>Marca</th>
                <td>{{ product.marca }}</td>
            </tr>
            <tr>
                <th>Categoria_id</th>
                <td>{{ product.categoriaId }}</td>
            </tr>
            <tr>
                <th>Precio</th>
                <td>{{ product.precio }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('product_index') }}">back to list</a>

    <a href="{{ path('product_edit', {'id': product.id}) }}">edit</a>

    {{ include('product/_delete_form.html.twig') }}
{% endblock %}